
#spring.datasource.url=jdbc:mysql://localhost:3306/prueba_pragma_bd?serverTimezone=UTC
#spring.datasource.username= root
#spring.datasource.password=123456

#spring.jpa.hibernate.ddl-auto= update
#spring.jpa.show-sql=true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prueba_pragma_bd?serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

